mod extended_system_exclusive;
mod utility;
mod message;
mod midi1_channel_voice;
mod midi2_channel_voice;
mod packet;
mod system_common;
mod system_exclusive;

pub use extended_system_exclusive::Message as ExtendedSysExMessage;
pub use extended_system_exclusive::DeserializeError as ExtendedSysExDeserializeError;
pub use utility::Message as UtilityMessage;
pub use utility::DeserializeError as UtilityDeserializeError;
pub use message::Message;
pub use message::DeserializeError;
pub use midi1_channel_voice::Message as Midi1ChannelVoiceMessage;
pub use midi1_channel_voice::DeserializeError as Midi1ChannelVoiceDeserializeError;
pub use midi2_channel_voice::Message as Midi2ChannelVoiceMessage;
pub use midi2_channel_voice::DeserializeError as Midi2ChannelVoiceDeserializeError;
pub use packet::Packet;
pub use system_common::Message as SysCommonMessage;
pub use system_common::DeserializeError as SysCommonDeserializeError;
pub use system_exclusive::Message as SysExMessage;
pub use system_exclusive::DeserializeError as SysExDeserializeError;

type Channel = u8;
type Controller = u8;
type Group = u8;
type Note = u8;
type Program = u8;
type Value = u8;
type Velocity = u8;
