mod assignable_controller;
mod assignable_per_note_controller;
mod attribute;
mod channel_pitch_bend;
mod channel_pressure;
mod control_change;
mod controllers;
mod helpers;
mod key_pressure;
mod note_off;
mod note_on;
mod per_note_management;
mod per_note_pitch_bend;
mod program_change;
mod registered_controller;
mod registered_per_note_controller;
mod relative_assignable_controller;
mod relative_registered_controller;

pub(crate) const TYPE_CODE: ux::u4 = ux::u4::new(0x4);

pub use attribute::Attribute as NoteAttribute;
pub use controllers::Controller;

pub use assignable_controller::AssignableControllerBuilder;
pub use assignable_controller::AssignableControllerMessage;
pub use assignable_per_note_controller::Builder as AssignablePerNoteControllerMessageBuilder;
pub use assignable_per_note_controller::Message as AssignablePerNoteControllerMessage;
pub use channel_pressure::ChannelPressureBuilder;
pub use channel_pressure::ChannelPressureMessage;
pub use control_change::ControlChangeBuilder;
pub use control_change::ControlChangeMessage;
pub use key_pressure::KeyPressureBuilder;
pub use key_pressure::KeyPressureMessage;
pub use note_off::NoteOffBuilder;
pub use note_off::NoteOffMessage;
pub use note_on::NoteOnBuilder;
pub use note_on::NoteOnMessage;
pub use per_note_management::Builder as PerNoteManagementMessageBuilder;
pub use per_note_management::Message as PerNoteManagementMessage;
pub use per_note_pitch_bend::PerNotePitchBendBuilder;
pub use per_note_pitch_bend::PerNotePitchBendMessage;
pub use channel_pitch_bend::ChannelPitchBendBuilder;
pub use channel_pitch_bend::ChannelPitchBendMessage;
pub use program_change::ProgramChangeBuilder;
pub use program_change::ProgramChangeMessage;
pub use registered_controller::RegisteredControllerBuilder;
pub use registered_controller::RegisteredControllerMessage;
pub use registered_per_note_controller::Builder as RegisteredPerNoteControllerMessageBuilder;
pub use registered_per_note_controller::Message as RegisteredPerNoteControllerMessage;
pub use relative_assignable_controller::RelativeAssignableControllerBuilder;
pub use relative_assignable_controller::RelativeAssignableControllerMessage;
pub use relative_registered_controller::RelativeRegisteredControllerBuilder;
pub use relative_registered_controller::RelativeRegisteredControllerMessage;
