mod assignable_per_note_controller;
mod attribute;
mod channel_effect;
mod control_change;
mod controller;
mod controllers;
mod helpers;
mod note;
mod per_note_effect;
mod per_note_management;
mod program_change;
mod registered_per_note_controller;

use channel_effect::pitch_bend;
use channel_effect::pressure as channel_pressure;
use controller::assignable as assignable_controller;
use controller::registered as registered_controller;
use controller::relative_assignable as relative_assignable_controller;
use controller::relative_registered as relative_registered_controller;
use note::note_off;
use note::note_on;
use per_note_effect::key_pressure;
use per_note_effect::pitch_bend as per_note_pitch_bend;

const TYPE_CODE: ux::u4 = ux::u4::new(0x4);

pub use attribute::Attribute as NoteAttribute;
pub use controllers::Controller;

pub use assignable_controller::Builder as AssignableControllerMessageBuilder;
pub use assignable_controller::Message as AssignableControllerMessage;
pub use assignable_per_note_controller::Builder as AssignablePerNoteControllerMessageBuilder;
pub use assignable_per_note_controller::Message as AssignablePerNoteControllerMessage;
pub use channel_pressure::Builder as ChannelPressureMessageBuilder;
pub use channel_pressure::Message as ChannelPressureMessage;
pub use control_change::Builder as ControlChangeMessageBuilder;
pub use control_change::Message as ControlChangeMessage;
pub use key_pressure::Builder as KeyPressureMessageBuilder;
pub use key_pressure::Message as KeyPressureMessage;
pub use note_off::Builder as NoteOffMessageBuilder;
pub use note_off::Message as NoteOffMessage;
pub use note_on::Builder as NoteOnMessageBuilder;
pub use note_on::Message as NoteOnMessage;
pub use per_note_management::Builder as PerNoteManagementMessageBuilder;
pub use per_note_management::Message as PerNoteManagementMessage;
pub use per_note_pitch_bend::Builder as PerNotePitchBendMessageBuilder;
pub use per_note_pitch_bend::Message as PerNotePitchBendMessage;
pub use pitch_bend::Builder as PitchBendMessageBuilder;
pub use pitch_bend::Message as PitchBendMessage;
pub use program_change::Builder as ProgramChangeMessageBuilder;
pub use program_change::Message as ProgramChangeMessage;
pub use registered_controller::Builder as RegisteredControllerMessageBuilder;
pub use registered_controller::Message as RegisteredControllerMessage;
pub use registered_per_note_controller::Builder as RegisteredPerNoteControllerMessageBuilder;
pub use registered_per_note_controller::Message as RegisteredPerNoteControllerMessage;
pub use relative_assignable_controller::Builder as RelativeAssignableControllerMessageBuilder;
pub use relative_assignable_controller::Message as RelativeAssignableControllerMessage;
pub use relative_registered_controller::Builder as RelativeRegisteredControllerMessageBuilder;
pub use relative_registered_controller::Message as RelativeRegisteredControllerMessage;
