mod assignable_controller;
mod assignable_per_note_controller;
mod attribute;
mod channel_effect;
mod control_change;
mod controllers;
mod helpers;
mod note_off;
mod note_on;
mod per_note_effect;
mod per_note_management;
mod program_change;
mod registered_controller;
mod registered_per_note_controller;
mod relative_assignable_controller;
mod relative_registered_controller;

use channel_effect::pitch_bend;
use channel_effect::pressure as channel_pressure;
use per_note_effect::key_pressure;
use per_note_effect::pitch_bend as per_note_pitch_bend;

pub(crate) const TYPE_CODE: ux::u4 = ux::u4::new(0x4);

pub use attribute::Attribute as NoteAttribute;
pub use controllers::Controller;

pub use assignable_controller::AssignableControllerBuilder;
pub use assignable_controller::AssignableControllerMessage;
pub use assignable_per_note_controller::Builder as AssignablePerNoteControllerMessageBuilder;
pub use assignable_per_note_controller::Message as AssignablePerNoteControllerMessage;
pub use channel_pressure::Builder as ChannelPressureMessageBuilder;
pub use channel_pressure::Message as ChannelPressureMessage;
pub use control_change::ControlChangeBuilder;
pub use control_change::ControlChangeMessage;
pub use key_pressure::Builder as KeyPressureMessageBuilder;
pub use key_pressure::Message as KeyPressureMessage;
pub use note_off::NoteOffBuilder;
pub use note_off::NoteOffMessage;
pub use note_on::NoteOnBuilder;
pub use note_on::NoteOnMessage;
pub use per_note_management::Builder as PerNoteManagementMessageBuilder;
pub use per_note_management::Message as PerNoteManagementMessage;
pub use per_note_pitch_bend::Builder as PerNotePitchBendMessageBuilder;
pub use per_note_pitch_bend::Message as PerNotePitchBendMessage;
pub use pitch_bend::Builder as PitchBendMessageBuilder;
pub use pitch_bend::Message as PitchBendMessage;
pub use program_change::Builder as ProgramChangeMessageBuilder;
pub use program_change::Message as ProgramChangeMessage;
pub use registered_controller::RegisteredControllerBuilder;
pub use registered_controller::RegisteredControllerMessage;
pub use registered_per_note_controller::Builder as RegisteredPerNoteControllerMessageBuilder;
pub use registered_per_note_controller::Message as RegisteredPerNoteControllerMessage;
pub use relative_assignable_controller::RelativeAssignableControllerBuilder;
pub use relative_assignable_controller::RelativeAssignableControllerMessage;
pub use relative_registered_controller::RelativeRegisteredControllerBuilder;
pub use relative_registered_controller::RelativeRegisteredControllerMessage;
