[package]
edition = "2021"
name = "handling_messages"
publish = false
version = "0.0.0"

[dependencies]
midi2 = { path = "../../midi2", default-features = false, features = [
    "channel-voice2",
    "sysex7",
] }
