name: Clippy
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
env:
  CARGO_TERM_COLOR: always
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-features -- -D warnings
